name: ProjectENV
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - nodejs

  - pandas
  - numpy
  - scipy
  - jupyter
  - scikit-learn
  - tqdm
  - torchtext
  - torchvision
  - jupyterlab
  - pytest-xdist
  - mkl
  - ipython
  - matplotlib
  - pytest
  - cudatoolkit
  - pip:
    - datasets
    - huggingface-hub
    - tokenizers
    - safetensors
    - diffusers
