name: ProjectENV
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - nodejs

  - pandas
  - numpy
  - scipy
  - scikit-learn
  - tqdm
  - matplotlib
  - jupyterlab
  - pytest
  - pytest-xdist
  - mkl
  - pip:
    - datasets
    - opencv-python
    - huggingface-hub
    - tokenizers
    - safetensors
    - diffusers
    - transformers
    - accelerate
